### ISSUE TITLE
[Bug] #1504 包含自定义组件时 import not found: compareSync 复现成功

### ISSUE THREAD

**Issue by lixiang810** [vuepress-theme-hope/vuepress-theme-hope#1518]
## Describe the bug

复现步骤：

1. clone [该 repo](https://github.com/lixiang810/tppi)
2. pnpm i
3. pnpm dev 或 pnpm clean-dev
4. 浏览器 console 输出：`import not fount: compareSync`

如果上一步没有成功复现，可以试着 `pnpm add vue`，之后再 `pnpm clean-dev`，应该可以稳定复现。

## Additional context

环境：Windows 11
浏览器：Mozilla Firefox Nightly 和 Microsoft Edge
Node 版本：Nodejs 16.14.0
pnpm 版本：6.32.2

**Comment by Mister-Hope** [comment]
This is out of scope of "A bug report"

I have no responsibility for any broken behavior when importing third-party UI libaraies. I don't know and don't want to waste my time reading their codes.

If your problem exists even without importing any components, welcome to open a new issue.

----

I guess the issue comes from `vue-demi` in `native-ui`, and you may actually getting two different vue instance in vuepress and native-ui.
