### ISSUE TITLE
[Bug] Spacing between words broken in Thai language

### ISSUE THREAD

**Issue by sakuhanachan** [vuepress-theme-hope/vuepress-theme-hope#1551]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/2475440/157038939-3dca4a87-31bc-40e6-819f-bdc2eebdf015.png)

**Comment by Mister-Hope** [comment]
1. I never used Thai language
2. I haven't used  <ruby> and <rp> <rt> tag before seeing your issue, so I am not editing their styles.
3. I can not find a reproduction link, also I am not sure what is expected.

So:

1. Could you please try to find out what happens and what should I do? E.g.: adding styles?
2. If you cannot done 1, could you provide a reproduction link of your site, and also provide along with same content rendered directly with another html and display as your expected?

If you cannot help with anything above, then I am afarid I don't know what to do.

**Comment by sakuhanachan** [comment]
Here's my repo and test site.
Repo: https://github.com/sakuhanachan/testsite
Test rendered site: https://sakuhanachan.github.io/testsite/posts/2018-12-31-kns2-drama-cd-summary.html

As my expect it should be like this.
![image](https://user-images.githubusercontent.com/2475440/157091227-9ea560dc-ddb1-4074-a70b-931c876baa9c.png)
([From My production site with Vuepress v1 and meteorlxy theme](https://blog.katsuragigroup.net/posts/2018/12/31/kns2-drama-cd-summary.html))

**Comment by Mister-Hope** [comment]
https://user-images.githubusercontent.com/33315834/157240223-5b41deae-598e-405f-b5bb-fc16f0456832.mp4

If this is what your are expecting, all you need to do is adding this style in `.vuepress/styles/index.scss`

```scss
.theme-hope-content:not(.custom)>p,
.theme-hope-content:not(.custom)>ol p,
.theme-hope-content:not(.custom)>ul p {
  text-align: left;
}
```

**Comment by Mister-Hope** [comment]
Resons:

I prefer to regard this as a normal behavior. The reson you see spaces is that ruby tag is not allowed to cross lines by default, and I am setting justify for text align. (The default is left) If you used Microsoft word, Goggle docs or anything like that before, you should probably know the difference between left right center and justify aligning.

And for Thai, the browser is treating them as words (as you use space to sperate between your characters, so when a line only have 2 or 3 of them, and have spare spaces, it will put the space between the words. (It happends because the next word(s) is wrapped by `<ruby>`, it will remain in the next line if the is not enough space for it in current line)

**Comment by Mister-Hope** [comment]
Also, I am not expecting people will use tags contianing `display: block` tag that can not be cutted between lines like `ruby` tag very often. When tag like this are used, the `justify` alian is expected to be not graceful.
