### ISSUE TITLE
[Bug] sitemap2 not working - Cannot read properties of undefined (reading 'lang')

### ISSUE THREAD

**Issue by okalachev** [vuepress-theme-hope/vuepress-theme-hope#1677]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-plugin-sitemap2

### Version

v2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Building the site with `vuepress build` falling with error:

```
✖ Generating sitemap to sitemap.xml - failed
error error in hook onGenerated from vuepress-plugin-sitemap2
TypeError: Cannot read properties of undefined (reading 'lang')
    at /XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:1436
    at Array.map (<anonymous>)
    at /XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:1416
    at Array.forEach (<anonymous>)
    at /XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:1006
    at /XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:1678
    at new Promise (<anonymous>)
    at /XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:562
    at /XXX/docs/node_modules/@vuepress/utils/lib/withSpinner.js:12:30
    at i (/XXX/docs/node_modules/vuepress-plugin-sitemap2/lib/node/index.js:1:556)
```

Where am I supposed to set the `lang` key?

My `config.js` (truncated):

```js
const hostname = 'xxx.xxx';

module.exports = {
	lang: 'en-US',
	title: 'XXX',
	theme: '@vuepress/theme-default',
	themeConfig: {
		sidebar: {
			'/ru/': <XXX>,
			'/en/': <XXX>,
		},
		locales: {
			'/en/': {
				selectLanguageName: 'English',
				navbar: <XXX>
			},
			'/ru/': {
				selectLanguageName: 'Русский',
				navbar: <XXX>
			},
		},
		// ...
	},
	locales: {
		'/en/': {
			lang: 'en',
			title: <XXX>,
			description: <XXX>
		},
		'/ru/': {
			lang: 'ru',
			title: <XXX>,
			description: <XXX>
		}
	},
	plugins: [
		'@vuepress/plugin-search',
		'vuepress-plugin-copy-code2',
		['sitemap2', { hostname }]
	],
	// ...
}
```

### Additional context

Versions:

```
vuepress/core@2.0.0-beta.38 vuepress/cli@2.0.0-beta.38 darwin-arm64 node-v17.5.0
```

**Comment by Mister-Hope** [comment]
I probably need your repo.

This issue is probably related to your markdown structure, because this error is triggered when getting lang of a page

**Comment by Mister-Hope** [comment]
I think I am getting why you met this problem. VuePress is prefered with a `/` locale as default locales, and you are not configuring it.

Try to make a minial reproduction to see if it's caused by that.

Also, you should use 

```
	themeConfig: {
		locales: {
			'/en/': {
				selectLanguageName: 'English',
				navbar: <XXX>,
	                        sidebar: {
			              '/en/': <XXX>,
		               },
			},
			'/ru/': {
				selectLanguageName: 'Русский',
				navbar: <XXX>,
                                 sidebar: {
			              '/ru/': <XXX>,
		               },
			},
		},
		// ...
	},

**Comment by okalachev** [comment]
@Mister-Hope, you can check the current state of the repo here: https://github.com/CopterExpress/clover/blob/vuepress/docs/.vuepress/config.js.

Do I understand correctly, that using the plugin is impossible without a locale on `/`? I don't want to have any locale on `/`, just language selection page.

**Comment by Mister-Hope** [comment]
Working situation:

- If your do not configue `locales` option, everything works fine
- If you configue `locales` option, and every page has a locale bind to it, everything works fine too.

----

Reason why it breaks:

Your problem is that you have a README.md at root, and you are not setting `locales["/"]``, also you are not excluding this page  from the plugin.

VuePress finds your `README.md`, then mark it with locale `/`, but the plugin can not find `locale["/"]` to get what language is that page, so the plugin throws an error.


----

Solution:


You must configue a locale for `/` or remvoe your `README.md` in root.

**Comment by Mister-Hope** [comment]
Anyway, I make https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/4306758d8ab942c041b937ee528789cad7e2bb3e to try not throwing errors.

**Comment by okalachev** [comment]
@Mister-Hope, I have updated the package to version `2.0.0-beta.41` and still got the same error. It seems like the compiled code in `lib` directory in not update, is this possible?

> The best way for you to do this is exclude that page from sitemap plugin, so that it won't be inferred as a page with alternate language.

How to do that? Should I add `excludeUrls: ['README.md']` or ...?

**Comment by Mister-Hope** [comment]
The fix is still in main.

`excludeUrls: ['/']`

**Comment by Mister-Hope** [comment]
Beta.43 release, and you won't meet errors with the original code. But the sitemap is incorrect though (just as a reminder)

**Comment by okalachev** [comment]
Great, thanks!

But why is it incorrect? I don't get it.

**Comment by Mister-Hope** [comment]
Your problem is that you have a README.md at root, and you are not setting `locales["/"]`, also you are not excluding this page from the plugin.

VuePress finds your README.md, then mark it with locale /, but the plugin can not find locale["/"] to get what language is that page, so the plugin throws an error.

---

The above is where there is an issue.

This also means that your homepage is treated as an alternate version of the actual 2 language homepage. But it's actually not. And the absent language information is default top English

**Comment by Mister-Hope** [comment]
So to have a correct sitemap, you should exclude that special page
