### ISSUE TITLE
[Feature Request] 能否指定导航栏的repo type？

### ISSUE THREAD

**Issue by ikechan8370** [vuepress-theme-hope/vuepress-theme-hope#1679]
### Describe the feature

我看到识别导航栏的repo type的相关代码是这样的，会根据repo的地址识别为github、bitbucket、gitlab或gitee，能否支持自定义设置type以及icon？
```
export type RepoType = "GitHub" | "GitLab" | "Gitee" | "Bitbucket" | null;

export const resolveRepoType = (repo: string): RepoType =>
  !isLinkHttp(repo) || /github\.com/.test(repo)
    ? "GitHub"
    : /bitbucket\.org/.test(repo)
    ? "Bitbucket"
    : /gitlab\.com/.test(repo)
    ? "GitLab"
    : /gitee\.com/.test(repo)
    ? "Gitee"
    : null;
```
现在输入私有的gitlab地址会变成Source，那个图标尺寸似乎有些问题，不太好看。

**Comment by Mister-Hope** [comment]
你可以发一个PR，把那个图标调一下。

**Comment by Mister-Hope** [comment]
I struggled a couple of minute, and can not find a unhacky way to provide icon customize feature. Because user can specific different repo for different languages, so that the Icon must be resolve at client side, or the each locale should bind a icon with it.

Both of them are a bit hacky

Currectly you should be able to use GithubIcon in the following way:

1. use `alias option to overide `@theme-hope/module/navbar/components/icon`:

   ```ts
   export default defineHopeConfig({
      // ...
     alias: {
       "@theme-hope/module/navbar/components/icon": path.resolve(__dirname, 'components/navbarIcon.js)
     }
   }
   ```

   > https://vuepress-theme-hope.github.io/v2/cookbook/advanced/replace.html#replace-components


1. add these:

```js
export * from "vuepress-theme-hope/lib/client/module/navbar/components/icons/i18nIcon";
export * from "vuepress-theme-hope/lib/client/module/navbar/components/icons/outlookIcon";
export {
  GitHubIcon,
  GiteeIcon,
  GitlabIcon,
  BitbucketIcon,
  GitHubIcon as SourceIcon,
} from "vuepress-theme-hope/lib/client/module/navbar/components/icons/repoIcon";
```

**Comment by ikechan8370** [comment]
Thank you, I'll try it.
