### ISSUE TITLE
Back to list animation on mobile

### ISSUE THREAD

**Issue by viktorprogger** [vuepress-theme-hope/vuepress-theme-hope#1930]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Animation of getting back to article list from an article page is jerking on mobile, see the video:

https://user-images.githubusercontent.com/7670669/171167480-9f1aa7fb-b324-43af-8033-4ee70e4f4cd1.mp4

**Comment by Mister-Hope** [comment]
Your behavior is expected on my side, if you have any improvement, pr welcome

**Comment by viktorprogger** [comment]
Is this ok for you?
1. I see the article list
2. It disappears with an animation
3. It appears again with an animation

In my opinion there should be just 1 point of these three: either it appears with or without animation, but it appears only once.

**Comment by Mister-Hope** [comment]
I hope you can understand why it’s behaving like this with this video. If you back to the page, every thing works fine. But if you swipe back, you will get a “snapshot” of the page when you leave that page, so all the transition elements shrinks for a few frames, then disappear and appear again with transition as expected.

that’s the behavior of browsers, which is not fixable in developer side. Actually, I would like to see someone pointing out a way to all the developers about how to fix this. So my point again, this is expected for me, and unless you come with a solution solving this, I won’t treat this expected behavior as a bug, and that’s why I close this with those tags. Is everything clear enough at this moment for you?

https://user-images.githubusercontent.com/33315834/171180471-1d3ccf3a-c4eb-4791-8020-3edfc922a3a1.MOV

**Comment by viktorprogger** [comment]
Oh, that's sad :( Thank you for such a descriptive answer.
