### ISSUE TITLE
[Bug] md-enhance include directive can not process related image path to display

### ISSUE THREAD

**Issue by snowyu** [vuepress-theme-hope/vuepress-theme-hope#2142]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope/packages/md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

The `include` directive can not process the related image path correctly.

The image can be only viewed in the original document.

* file: ./guide/get-started/intro.md

```md
Some pics to includes

![img](./apic.jpg)

## Other not include

```

* file: ./another-file,md

```md
@include(./guide/get-started/intro.md{1-3})
```

**Comment by Mister-Hope** [comment]
thanks for the detailed information. But we will need some discussion here.

Personally, I think you might need to use alias for that images, that can be a workaround at any time. As for this report, I think this is pretty reasonable, but it's hard to support this feature because we can actually include any files. And this feature is also described as including file content, so we are not actually parsing content while including.


To make images or links regenerated we need to actually parse the markdown file, and that's obeying the actual priority because this is actually done before parsing the original markdown.

Also some people may store snippets in one place, and they would actually want to keep the link as is.

**Comment by snowyu** [comment]
I'm a newbie to vuepress. But know a little about markdown-it.

1. Check the include file whether the markdown file is not the problem
2. The problem is when to parse the markdown file. But maybe do not need to parse the markdown file.

Maybe can add some helper markdown directives to remember the current included markdown file path:

```md
@include-push /the/absolute-path/guide/get-started/
Some pics to includes

![img](./apic.jpg)

@include-push /the/absolute-path/guide/other-dir/
![img](./apic.jpg)
@include-pop

@include-pop
```

The `handleInclude` func can wrapped the embed markdown content with the `@include-push` and `@include-pop`.

Then override the default `link` and `image` rules to rewrite the path.

**Comment by Mister-Hope** [comment]
Anyway, pr welcomed to provide such a feature with 2 new option `convertLinks: boolean` and `convertImages: boolean`
