### ISSUE TITLE
[Bug] Mathjax CHTML not working

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#2231]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

CHTML output not working. This is because we can not get the style being injected properly.

### Additional context

Can use svg as a workaround

**Comment by init-qy** [comment]
The tag style can take effect in html body, so I try it and it does work.
```js
const renderMath = (
  content: string,
  documentOptions: DocumentOptions,
  displayMode: boolean
): string => {
  const adaptor = liteAdaptor();

  RegisterHTMLHandler(adaptor);
  const mathDocument = MathJax.document(content, documentOptions);
  /* eslint-disable */
  const html = adaptor.outerHTML(
    mathDocument.convert(content, { display: displayMode })
  );
  const stylesheet = adaptor.innerHTML(
    documentOptions.OutputJax.styleSheet(mathDocument)
  );

  return `${html}<component is="style">${stylesheet}</component>`;
};
```

The problem is that `stylesheet` contains duplicate codes(about 500 lines), if I have 10+ mathjax in one page, It will turn into a disaster.

The another problem is the `fontPath`, I change it to cdn, and it works well, but I dont know how to resolve from local.

For more you can see [my fork repo](https://github.com/init-qy/vuepress-theme-hope/commit/bd1cdd8aba614b96bd0e2e4c630d14fcba5240c0)

Hope to help you
