### ISSUE TITLE
[Question] `date` in frontmatter treated as UTC time

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2405]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="960" alt="image" src="https://user-images.githubusercontent.com/48122016/201454897-c14549c4-8eff-44fc-b22c-21fbb44c52d5.png">
文档日期，与部署后的日期：

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/201454909-cc694898-44ad-4202-a801-8b18816b2517.png">
本地构建，部署到服务器

**Comment by Mister-Hope** [comment]
Interesting 🤔

**Comment by AndersonHJB** [comment]
我也这么觉得，好奇怪的呢，我试了两台电脑也是😂

**Comment by Mister-Hope** [comment]
I got why the issue is. This is a timezone problem.

When we have a date format like one in your screenshot, it can have 2 meanings:

1. The date is an absolute date in utc (in another word it shall add 8 hours in Asia/Shanghai)
2. The date is a local time, which means it's not the same moment when you open this in different places.

Most ci environment use utc timezone, also the display should be the same when opening the site in different timezones, so the theme will pretend that all the Date are at utc (utc0).

However, your machine is in utc-8, which means that 21h is next day in utc-8.

**Comment by Mister-Hope** [comment]
I got why the issue is. This is a timezone problem.

When we have a date format like one in your screenshot, it can have 2 meanings:

1. The date is an absolute date in utc (in another word it shall add 8 hours in Asia/Shanghai)
2. The date is a local time, which means it's not the same moment when you open this in different places.

Most ci environment use utc timezone, also the display should be the same when opening the site in different timezones, so the theme will pretend that all the Date are at utc (utc0).

However, your machine is in utc-8, which means that 21h is next day in utc-8.

Edited: Nope, the explaination can not fit itself. I will check my codes.

**Comment by AndersonHJB** [comment]
时区问题那和 Django 一些网站确实一样，但是会有个小疑惑，是部分页面会产生这样的问题，我也很高兴我的描述可以让你理解原因。补充一个问题：有些明明写日期了，但是显示没有日期，这个也是最近出现的问题。「PS：都是最新版本」
<img width="848" alt="image" src="https://user-images.githubusercontent.com/48122016/201461072-fe3c9a53-729e-4c52-9b66-3851f72d93e6.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/48122016/201461087-ec3f6ce8-528c-4066-b99a-d25a5a12583b.png">

**Comment by Mister-Hope** [comment]
This cannot be fixed as VuePress already parsed the date string as UTC timezone time.

**Comment by Mister-Hope** [comment]
> 时区问题那和 Django 一些网站确实一样，但是会有个小疑惑，是部分页面会产生这样的问题，我也很高兴我的描述可以让你理解原因。补充一个问题：有些明明写日期了，但是显示没有日期，这个也是最近出现的问题。「PS：都是最新版本」 <img alt="image" width="848" src="https://user-images.githubusercontent.com/48122016/201461072-fe3c9a53-729e-4c52-9b66-3851f72d93e6.png"> <img alt="image" width="692" src="https://user-images.githubusercontent.com/48122016/201461087-ec3f6ce8-528c-4066-b99a-d25a5a12583b.png">

Needs reproduction.
