### ISSUE TITLE
[Feature Request]内置组件能否考虑支持props传参数

### ISSUE THREAD

**Issue by liub1934** [vuepress-theme-hope/vuepress-theme-hope#2562]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

以`@theme-hope/modules/blog/components/ProjectPanel.js`组件为例子，我看源码数据是从`frontmatter.value.projects`里面取的，是否也可以新增从props里面取数据，如下所示：

<img width="906" alt="image" src="https://user-images.githubusercontent.com/29849550/208283442-50932d0f-034d-4ef0-b22c-2fc1a3c878af.png">

新增props传参后以满足在同一页面上可以多处调用使用，自定义更强些。

<img width="591" alt="image" src="https://user-images.githubusercontent.com/29849550/208283627-82e27997-0914-40f5-af35-ac831406a5ab.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/29849550/208283610-b75a0ac3-2ad2-4fa7-89b4-708ee59ab6a4.png">

**Comment by Mister-Hope** [comment]
It's possible for you to do component replacement with `alias`, and I am not expecting to add any code which is used in edge case for everyone.

Or in another word:

1. You are using with an edge case as rare people would import theme component to use this in page
2. Edge case code for "unnormal usage" shall not be added as every one will get the code in production
3. We provide alias for you to replace component, so unless the component is actually "A part of a big component"(e.g.: those in navbar and sidebar), they shall not preferred to receive data from parent, instead they shall implement something by their own, so that users can easily replace them to get what they want instead of studying parent component to learn where the data is from.

**Comment by Mister-Hope** [comment]
Also I have to warn you you are displaying a piece of uncorrect code in Vue, projects in your screenshot is losing reactivity.
