### ISSUE TITLE
[Feature Request] 设置侧边栏children的图标默认值为页面图标

### ISSUE THREAD

**Issue by SherkeyXD** [vuepress-theme-hope/vuepress-theme-hope#3351]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在如下的设置中
```ts
import { defineUserConfig } from "vuepress";
import { hopeTheme } from "vuepress-theme-hope";

export default defineUserConfig({
  theme: hopeTheme({
    sidebar: [
      // ...
      {
        text: "example",
        children: [
          "/test.md",
          {
            text: "test-with-title",
            link: "/test.md",
          }
        ],
      },
    ],
  }),
});

```
第一个子项目在侧边栏中能够显示图标而第二个不能（md文件中指定了图标）
原因应该是第二个子项目没有默认icon值，导致不显示
希望能把icon的默认值设置为页面icon（或者留个开关？

**Comment by Mister-Hope** [comment]
Using object configuration means you want full control of sidebar (even the link does not exisit or be a link outside vuepress routes)

**Comment by Alex6357** [comment]
How about setting the default behavior to fallback to the icon defined in the markdown when the icon property is not used, and only hide the icon when an empty string or null is explicitly passed? I think this approach would be better.

**Comment by Mister-Hope** [comment]
There is a config called `shortTitle` in frontmatter which is preferred for breadcrumbs and sidebars, so I did NOT see any motivation that you are willing to choose "an object way" instead of a direct link with string.

Again, object way is designed for **advanced usage or full control**. Any invisible or fallback behavior only makes users more confused when using it.

New discussions are welcomed for cases like this, rather than any old issue which has been closed.
