### ISSUE TITLE
[Bug] md 文件间跳转或搜索定位时，图片加载导致目标位置偏移

### ISSUE THREAD

**Issue by prgding** [vuepress-theme-hope/vuepress-theme-hope#3435]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

跳转到 b.md 的 # 3 时因图片加载导致页面位置偏移

### Additional context

问题描述:
当从 a.md 文件中点击一个链接，目标是 b.md 中的 # 3 大标题时 (假设页面中从上往下有 # 1, # 2, # 3 这些大标题)，如果 b.md 中 # 3 大标题之上有图片，页面的位置会因图片加载而发生偏移。

重现步骤:
在 a.md 中创建一个链接指向 b.md 的 # 3 大标题。
确保 b.md 在 # 3 标题之上有至少一个图片。
开启浏览器开发者工具，将网络速度模拟为3G。
从 a.md 点击链接跳转到 b.md。

预期结果:
页面应该准确地跳转到 b.md 的 # 3 大标题，并且保持该位置，即使图片完成加载。

实际结果:
在 b.md 页面中，最初正确地跳转到了 # 3 大标题。但是，当图片加载完成后，# 3 大标题被推下去，并且URL会自动更改为 # 3 之上的某个大标题（例如 # 2 或 # 1）。

**Comment by prgding** [comment]
增加标题

**Comment by prgding** [comment]
使用搜索定位时，也会出现同样的问题

**Comment by Mister-Hope** [comment]
Closing as we can not find a proper way to do this.

It's hard to determinate "what's on screen", and what's the behavior when image is loading and users are scrolling pages at the same time.

If any other similar tools achieve this feature, feedback is welcomed.

---

Workaround: use imgSize in md-enhance plugin (or css) to declare all image size, so that all images take proper spaces at first frame.
