### ISSUE TITLE
figure and imgMark don't work together

### ISSUE THREAD

**Issue by PieterHartog** [vuepress-theme-hope/vuepress-theme-hope#3641]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Thanks for the great tool, but I noticed the following issue:

I would like to use both imgMark and 'figure' features together.
At the moment, when I have figure=true and imgMark=true and I do this:

```
![Diagram 1](./img/AgileBoardCreateVersion-dark.png#dark)
![Diagram 2](./img/AgileBoardCreateVersion-light.png#light)
```

I see only one image based on the light/dark mode i'm in (that's good), but no captions under the images.

I tried this as well (line break between the two images:

```
![Diagram 1](./img/AgileBoardCreateVersion-dark.png#dark)

![Diagram 2](./img/AgileBoardCreateVersion-light.png#light)
```

When I'm in light mode, I see the caption of the first one (but no image) and the image and caption of the second (dark) image.

It would be nice if the figure captions would work with the imgMark.

**Comment by Mister-Hope** [comment]
https://caniuse.com/css-has  Note this is still a working draft

This could be done now,  But support rage is also a bit low to be considered.

Image Mark feature only adds attribute to image elements, 

Well, the figure feature is actually creating a new rule called figure before the image rule.

It's already complicated enough for all of these threeimage features working together,  But since figure feature converts an image element to a figure containing image and figure caption,  The figure caption is not controlled by the default style injected by img Mark,  That is figure must have a way to detected if it has a child containing specific attributes (img mark).

You can use the above the selector to done this by adding new style your project,  I don't want to add at this time because all stable version of firefox have not support this yet.

**Comment by PieterHartog** [comment]
Thanks for your consideration. I will close the issue.

**Comment by Mister-Hope** [comment]
Workaround:

```scss
@use '@sass-palette/hope-config';

#{hope-config.$light-selector} {
  figure:has(img[data-mode="darkmode-only"]) {
    display: none !important;
  }
}

#{hope-config.$dark-selector} {
  figure:has(img[data-mode="lightmode-only"]) {
    display: none !important;
  }
}
```

**Comment by Mister-Hope** [comment]
If it works, I would be happy to hear some feedback. We will add these types once firefox support this in latest version.
