### ISSUE TITLE
[Bug]copyright: false失效 photoSwipe: false失效

### ISSUE THREAD

**Issue by 006hjy** [vuepress-theme-hope/vuepress-theme-hope#3939]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

使用升级命令升级到最新版后，copyright: false无法关闭自带的copyright。md中的photoSwipe: false不起作用

**Comment by Mister-Hope** [comment]
photo-swipe issues now needs to be reported at https://github.com/vuepress/ecosystem.

For the copyright, I am not sure what you are talking, the footer copyright or copyright plugin. The plugin is not enable by default, so that setting `plugins.copyright` to `false` or just leave it undefined should does the same work. And for the footer copyrightm you'd better provide a minimal reproduction.

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/28d8a386-4fee-426d-bd36-3ac076fcb9a8)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/34a8cfc1-42d5-4b8e-b298-ab72a125de08)

Photoswipe is fixed upstream, a new issue with minimal reproduction about footer copyright is required.
