### ISSUE TITLE
single add “vuepress-plugin-copy-code2” ,report an error[Bug]

### ISSUE THREAD

**Issue by Zhengqbbb** [vuepress-theme-hope/vuepress-theme-hope#856]
verison: 2.0.0-alpha.5
## Describe the bug
I am using vuepress 2.x .And when i want to add vuepress-plugin-copy-code2 in my project, it report an error.

## Screenshots
![image](https://user-images.githubusercontent.com/40693636/128276736-6add60d6-6907-4e22-ae8d-611b856464a5.png)
my plugin config:
![image](https://user-images.githubusercontent.com/40693636/128276929-4983d150-aff8-4328-a4e4-0a996a202d5f.png)

## Additional context
please can update the README 
https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/copy-code2/readme.md

Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by Mister-Hope** [comment]
Hi, vuepress@v2 is still in progress, and my theme and plugins are only tested with vuepress@2.0.0-beta.17, and do not compatable with newer versions because of later breaking changes.

And now I do not have plans to keep finishing it untill vuepress@2 touch rc or stable.

So my suggestion is do not use my plugins now. Even if you fall back to beta.17, the update on tollchain may still break the project. meteorlxy is using some beta and rc deps like `webpack-dev-server@v4` on vuepress, so early versions may even not work now when the upstream deps making breaking changes itself.

Anyway, thanks for reporting, and welcome to take a look at this project again when vuepress touch rc or stable.
